app/recruits/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField, SelectField, StringField
from wtforms.validators import DataRequired

from app import models


class RecruitsForm(FlaskForm):
    def __init__(self, *args, **kwargs):
        super(RecruitsForm, self).__init__(*args, **kwargs)
        self.recruiter.choices = [(account.rsn, account.rsn) for account in
                                  models.Accounts.query]  # .filter(models.Accounts.in_clan == 'Yes')]
        self.recruiter.choices.extend([('***Unknown***', '***Unknown***'),
                                       ("***Alts***", "***Alts***"), ("***Founder***", "***Founder***")])
        self.recruiter.choices.sort(key=lambda t: tuple(t[0].lower()))

    recruit_date = DateField('Event Date', format='%Y/%m/%d')

    activity = SelectField("Activity Type Choices", choices=[('Join', 'Join'), ('Leave', 'Leave')],
                           validators=[DataRequired()])

    recruiter = SelectField("RSN Choices", validators=[DataRequired()])

    recruit = StringField('recruit', validators=[DataRequired()])

app/recruits/__init__.py
from flask import Blueprint


recruits = Blueprint('recruits', __name__)

from . import views

app/recruits/views.py
from datetime import datetime

import pandas as pd
from bokeh.charts import Bar
from bokeh.embed import components
from bokeh.resources import INLINE
from flask import flash, redirect, render_template, request, url_for
from flask_login import login_required
from flask_paginate import Pagination, get_page_args
from sqlalchemy import and_, desc, exists
from sqlalchemy.sql import func

from app import db, models
from app.caps.views import add_cap
from app.recruits.forms import RecruitsForm
from . import recruits

pd.set_option('display.max_colwidth', -1)


@recruits.route('/recruits', methods=['GET', 'POST'])
@login_required
def list_recruits():
    form = RecruitsForm(request.form)

    if request.method == 'POST':
        return add_recruit(form)

    page, per_page, offset = get_page_args()
    recruit_table = models.Recruits.query.order_by(desc(models.Recruits.id))
    recruit_table_render = recruit_table.limit(per_page).offset(offset)

    pagination = Pagination(page=page, per_page=per_page, offset=offset, total=recruit_table.count(),
                            record_name='recruit', css_framework='bootstrap3')

    return render_template('recruits/recruits.html', recruit_table=recruit_table_render,
                           pagination=pagination, title="Recruits",
                           action="recruits.list_recruits", form=form)


def add_recruit(form):
    if form.validate():
        if form.activity.data == 'Join':
            # Makes sure there isn't already a clan member with the same name (prevents double entry).
            if db.session.query(exists().where(and_(models.Accounts.in_clan == 'Yes',
                                                    models.Accounts.rsn == form.recruit.data))).scalar():
                flash('Someone by that RSN is already in the clan.')
                return redirect(url_for('recruits.list_recruits'))

            # Make sure the date isn't in the future
            if form.recruit_date.data > datetime.now().date():
                flash("That date's in the future. Since I'm pretty sure you're not psychic, please try another date.")
                return redirect(url_for('recruits.list_recruits'))

            # Adds the recruit to the Accounts list, if they're not rejoining
            if models.Accounts.query.filter(models.Accounts.rsn.ilike(form.recruit.data.replace(" ", "_") + "%")):
                account = models.Accounts.query.filter_by(rsn=form.recruit.data).first()
                account.in_clan = 'Yes'
            else:
                new_account = models.Accounts(rsn=form.recruit.data, in_clan='Yes', join_date=form.recruit_date.data)
                models.db.session.add(new_account)

            # Adds a cap of "New" for the new recruit
            new_cap = add_cap(form.recruit_date.data, form.recruit.data, "New")
            models.db.session.add(new_cap)
        else:
            # This check will be made redundant when there's a dropdown of current members to select from for leaves
            if not db.session.query(exists().where(and_(models.Accounts.in_clan == 'Yes',
                                                        models.Accounts.rsn == form.recruit.data))).scalar():
                flash('There\'s no one currently in the clan with that RSN.')
                return redirect(url_for('recruits.list_recruits'))

            # Makes sure the leave date wasn't set before the person even joined the clan.
            join_date = [date.join_date for date in models.Accounts.query.filter(
                models.Accounts.rsn == form.recruit.data)]
            if form.recruit_date.data < join_date[0]:
                flash("Player was not yet in the clan. Please select a date on or after {join_date}".format(join_date=join_date[0]))
                return redirect(url_for('recruits.list_recruits'))

            # Make sure the date isn't in the future
            if form.recruit_date.data > datetime.now().date():
                flash("That date's in the future. Since I'm pretty sure you're not psychic, please try another date.")
                return redirect(url_for('recruits.list_recruits'))

            account = models.Accounts.query.filter_by(rsn=form.recruit.data).first()
            account.in_clan = 'No'
            account.leave_date = form.recruit_date.data

        # Adds the activity to the Recruits table
        new_recruit = models.Recruits(form.recruit_date.data,
                                      form.activity.data,
                                      form.recruiter.data,
                                      form.recruit.data,
                                      points(form.recruit.data, form.activity.data, form.recruit_date.data),
                                      change_to_recruit_count(form.activity.data))

        models.db.session.add(new_recruit)

        # Recalculate total recruiting points and add to Accounts.recruit_points
        # Just need to sum all in Recruits.points for the rsn and multiply by 10

        try:
            models.db.session.commit()
            flash('Recruit activity successfully added!')
        except:
            flash('Something went wrong. Please try again.')

        # Update recruits for rank sheet
        a = models.Accounts.query.filter(models.Accounts.rsn == form.recruiter.data).first()
        a.recruit_points = models.Recruits.query.\
            filter_by(recruiter=form.recruiter.data).\
            with_entities(func.sum(models.Recruits.points)).all()[0][0]
        db.session.commit()

    else:
        flash('Fill the form completely and properly, dumb-dumb.')

    return redirect(url_for('recruits.list_recruits'))


@recruits.route('/recruits/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_recruit(id):
    recruit = models.Recruits.query.get_or_404(id)
    form = RecruitsForm(obj=recruit)

    if request.method == 'POST':
        if form.validate():
            previous_recruit_date = recruit.recruit_date

            recruit.recruit_date = form.recruit_date.data
            recruit.activity_type = form.activity.data
            recruit.recruiter = form.recruiter.data
            recruit.recruit = form.recruit.data

            change_to_recruit_count(form.activity.data)

            earlier_date = min(previous_recruit_date, recruit.recruit_date)

            # Updates current recruit entry and all future entries
            entries = [recruit for recruit in models.Recruits.query.filter_by(recruiter=recruit.recruiter).
                       filter(models.Recruits.recruit_date >= earlier_date).order_by(models.Recruits.recruit_date)]

            for entry in entries:
                entry.points = points(entry.recruit, entry.activity_type, entry.recruit_date)  # "Edit"

            try:
                db.session.add(recruit)
                db.session.commit()
                flash('You have successfully edited the recruiting entry.')
            except:
                flash('Something went wrong. Please try again.')

            # Update recruits for rank sheet
            a = models.Accounts.query.filter(models.Accounts.rsn == form.recruiter.data).first()
            a.recruit_points = models.Recruits.query. \
                filter_by(recruiter=form.recruiter.data). \
                with_entities(func.sum(models.Recruits.points)).all()[0][0]
            db.session.commit()

        else:
            flash('Fill the form completely and properly, dumb-dumb.')

        return redirect(url_for('recruits.list_recruits'))

    return render_template('recruits/recruit.html', action="recruits.edit_recruit", id=id, form=form,
                           title="Edit Recruit", button_text="Save Changes")


@recruits.route('/recruits/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_recruit(id):
    recruit = models.Recruits.query.get_or_404(id)
    db.session.delete(recruit)
    db.session.commit()
    flash('You have successfully deleted the recruit.')

    return redirect(url_for('recruits.list_recruits'))


def points(recruit, type, date):
    """Point awarded for joins, but taken away if the recruit leaves within 7 days"""
    if type == "Join":
        return 1
    else:
        x = models.Recruits.query.filter_by(recruit=recruit).order_by(desc(models.Recruits.id)).first()
        # todo change date and x.recruit_date to dates instead of strings
        days_in_clan = date - x.recruit_date
        if days_in_clan.days >= 7:
            return 0
        return -1


def change_to_recruit_count(type):
    if type == "Join":
        return 1
    return -1


@recruits.route('/viewrecruits', methods=['GET', 'POST'])
@login_required
def viewrecruits():
    df = pd.read_sql(models.Recruits.query.order_by(models.Recruits.recruit_date).statement, db.engine)

    # summary of recruiting by recruiter
    df['Total Recruits'] = df.groupby(['recruiter'])['change_to_recruit_count'].apply(lambda x: x == 1)
    df['Recruits Worth Points'] = df['points']
    df['Remaining Recruits'] = df['change_to_recruit_count']
    # also pull in_clan_or_not from Account ?

    retention_pivot = pd.pivot_table(df, index=["recruiter"],
                                     values=["Total Recruits", "Recruits Worth Points", "Remaining Recruits"],
                                     aggfunc=sum)

    retention_pivot['Retention Rate'] = retention_pivot['Remaining Recruits'] / retention_pivot['Total Recruits']
    right_order = ["Total Recruits", "Recruits Worth Points", "Remaining Recruits", "Retention Rate"]
    retention_pivot = retention_pivot.reindex(columns=right_order)
    retention_pivot.index.name = None

    # count by recruiter by day
    count_by_recruiter = pd.crosstab(index=df.recruit_date, columns=df.recruiter, values=df.change_to_recruit_count,
                                     aggfunc=sum, dropna=True, margins=False).fillna('')

    # cummulative count by recruiter over time; use for stacked bar chart

app/templates/recruits/recruit.html
<!-- extend base layuot -->
{% extends "layout.html" %}
{% block content %}

<div class="col-md-8">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-info" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <ul class = flashes>
                    {% for message in messages %}
                        {{message}}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-line-chart"></i> {{ title }} <a class="pull-right fa fa-question" href="#" style="text-decoration:none;"></a></h3>
        </div>

        <div class="panel-body">
            <form method="post" action="{{ url_for(action, id=id) }}" id="eventForm" class="form-horizontal">
                <div class="form-group">
                    {{ form.csrf_token }}
                    <label class="col-xs-3 control-label">Recruit Date</label>
                    <div class="input-group input-append date" id="datePicker">
                        {{ form.recruit_date(class_="form-control") }}
                        <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-3 control-label">Activity</label>
                    <div class="col-xs-12" name="Activity Type">
                        {{ form.activity(class_="form-control") }}
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-3 control-label">Recruiter</label>
                    <div class="col-xs-5 date">
                        <div class="input-group input-append date">
                            {{ form.recruiter(class_="form-control") }}
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-3 control-label">Recruit</label>
                    <div class="col-xs-5 date">
                        <div class="input-group input-append date">
                            {{ form.recruit(class_="form-control") }}
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-5 col-xs-offset-3">
                        <button type="submit" class="btn btn-default"> {{ button_text }} </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

app/templates/recruits/recruits.html
<!-- extend base layuot -->
{% extends "layout.html" %}
{% block content %}

<div class="col-md-8">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-info" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <ul class = flashes>
                    {% for message in messages %}
                        {{message}}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-line-chart"></i> Recruits <a class="pull-right fa fa-gear" href="#" style="text-decoration:none;"></a></h3>
        </div>
        <div class="panel-body">
            <table class="table" id="grid">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Activity Type</th>
                        <th>Recruiter</th>
                        <th>Recruit</th>
                        <th>Action(s)</th>
                    <tr>
                </thead>
                <tbody>
                    <tr>
                        <form method="post" action="{{ url_for(action) }}" id="eventForm" class="form-horizontal">
                            {{ form.csrf_token }}
                            <td>
                                <div class="input-group input-append date" id="datePicker">
                                    {{ form.recruit_date(class_="form-control") }}
                                    <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                                </div>
                            </td>

                            <td>
                                <div class="col-xs-12" name="Activity Type">
                                    {{ form.activity(class_="form-control") }}
                                </div>
                            </td>
                            <td>
                                <div class="col-xs-12" name="Recruiter">
                                    {{ form.recruiter(class_="form-control") }}
                                </div>
                            </td>

                            <td>
                                <div class="col-xs-12" name="Recruit">
                                    {{ form.recruit(class_="form-control") }}
                                </div>
                            </td>

                            <td>
                                <div class="col-xs-5 col-xs-offset-3">
                                    <button type="submit" class="btn btn-default"> <i class="fa fa-plus"></i> Add </button>
                                </div>
                            </td>
                        </form>
                    </tr>
                    {% for row in recruit_table %}
                    <tr>
                        <td>{{ row.recruit_date }}</td>
                        <td>{{ row.activity_type }}</td>
                        <td>{{ row.recruiter }}</td>
                        <td>{{ row.recruit }}</td>
                        <td>
                            <a href="{{ url_for('recruits.edit_recruit', id=row.id) }}">
                                <i class="fa fa-pencil"></i> Edit
                            </a>

                            <a href="{{ url_for('recruits.delete_recruit', id=row.id) }}">
                                <i class="fa fa-trash"></i> Delete
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="pagination-bar">
                {{ pagination.links }}
                {{ pagination.info }}
            </div>
        </div>
    </div>
</div>


<div class="col-md-4">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-keyboard-o"></i> Instructions/Notes </h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>Coming soon.</li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

app/templates/recruits/viewrecruits.html
<!-- extend base layuot -->
{% extends "layout.html" %}
{% block content %}

    {{ js_resources|indent(4)|safe }}
    {{ css_resources|indent(4)|safe }}
    {{ bar_script|indent(4)|safe }}

<div class="col-md-6">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-pie-chart"></i> Total Clan Members by Reccruiter Since Inception <a class="pull-right fa fa-gear" href="#" style="text-decoration:none;"></a></h3>
        </div>
        <div class="panel-body">
            {{ bar_div|indent(4)|safe }}
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-line-chart"></i> Recruit <a class="pull-right fa fa-gear" href="#" style="text-decoration:none;"></a></h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                {{ retention|safe }}
            </div>
        </div>
    </div>
</div>

{% endblock %}